---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role prospectus
#

# .env vars
PROSPECTUS_ENVIRONMENT: !!null
PROSPECTUS_OAUTH_ID: !!null
PROSPECTUS_OAUTH_SECRET: !!null
PROSPECTUS_OAUTH_URL: !!null
PROSPECTUS_DISCOVERY_PROGRAMS_URL: !!null
PROSPECTUS_DISCOVERY_COURSES_URL: !!null
PROSPECTUS_DISCOVERY_SUBJECTS_URL: !!null
PROSPECTUS_LMS_FOOTER_URL: !!null
PROSPECTUS_GATSBY_SITE_DOMAIN: !!null
PROSPECTUS_GATSBY_LMS_DOMAIN: !!null
PROSPECTUS_GATSBY_USER_ENROLLMENT_API: !!null
PROSPECTUS_GATSBY_USER_ENTITLEMENT_API: !!null
PROSPECTUS_MARKETING_DOMAIN: !!null

PROSPECTUS_COURSE_RUN_ENROLLMENT_API: /api/commerce/v0/baskets/
PROSPECTUS_USER_ENROLLMENT_API: /api/enrollment/v1/enrollment
PROSPECTUS_USER_ENTITLEMENT_API: /api/entitlements/v1/entitlements/
PROSPECTUS_DRUPAL_COURSE_API: /api/catalog/v2/courses/

PROSPECTUS_NEW_RELIC_LICENSE_KEY: 'fake-key'
PROSPECTUS_NEW_RELIC_APP_ID: 'fake-id'

# nginx vars
PROSPECTUS_DATA_DIR: '/edx/var/prospectus'
PROSPECTUS_PROXY_PASS: 'http://localhost:8080'
NGINX_PROSPECTUS_PROXY_INTERCEPT_ERRORS: true

# task vars
PROSPECTUS_GIT_IDENTITY: "none"
prospectus_repo: 'ssh://git@github.com/edx/prospectus.git'
prospectus_version: 'master'
edx_django_service_use_python3: false
prospectus_node_version:  '{{ common_node_version }}'
prospectus_service_name: 'prospectus'
prospectus_home: '{{ COMMON_APP_DIR }}/{{ prospectus_service_name }}'
prospectus_venv_dir: '{{ prospectus_home }}/venvs/{{ prospectus_service_name }}'
prospectus_nodeenv_dir: '{{ prospectus_home }}/nodeenvs/{{ prospectus_service_name }}'
prospectus_nodeenv_bin: '{{prospectus_nodeenv_dir}}/bin'
prospectus_app_dir: "{{ COMMON_APP_DIR }}/prospectus"
prospectus_user: 'root'
prospectus_env_vars:
  PATH: "{{ prospectus_nodeenv_bin }}:{{ prospectus_venv_dir }}/bin:{{ ansible_env.PATH }}"
  NODE_ENV: "{{ PROSPECTUS_ENVIRONMENT }}"
  ACTIVE_ENV: "{{ PROSPECTUS_ENVIRONMENT }}"
prospectus_git_ssh: /tmp/git_ssh.sh
prospectus_git_identity: "{{ prospectus_app_dir }}/prospectus-git-identity"
prospectus_code_dir: "{{ prospectus_app_dir }}/prospectus"
